# Python Libraries

In this lesson we will discuss some useful shortcuts for Jupyter, however the main topic is an introduction to using Python libraries. These are packages of software written in Python or other languages, which allow you to vastly extend the capability of Python. Generally, if you want to program something, the first thing you should do is check whether there is a library which can assist. Not only will this save you time, but the libraries are usually optimized to run much faster than code you may write. We will focus here on the standard mathematics library and `numpy`, which is a package designed for performing algebra with vectors and matrices.

## Contents:

* Jupyter Shortcuts
* Jupyter Magic Commands
* Importing and Using Libraries
    * The math library
    * Numpy
* Exercises

## Jupyter Shortcuts

Jupyter provides many keyboard shortcuts to make the development of code and notebooks quicker. You can even define your own shortcuts. Below we list a few of the most useful ones. To see more about shortcuts see Menu -> Help -> Keyboard Shortcuts.

You may already have noticed that Jupyter has two modes. These are:
* Editing mode, where there is a green border around the cell. This mode is activated by clicking on the cell.
* Command mode, where there is a blue border around the cell. This is activated by clicking on the cell border. 
Selecting cells and using the shortcuts occurs in Command mode.

The most common shortcuts in Command mode are:
* p - open command palette and search for commands (can also click on keyboard icon).
* 1-6 - create a heading in the cell of that order. Heading 1 is the top heading, and higher numbers are subheadings.
* m - convert the cell to Markdown (documentation mode).
* y - convert the cell to code (Python).
* r - convert the cell to raw (uninterpreted).
* a - insert a cell above the current cell.
* b - insert a cell below the current cell.
* [Shift][Return] - run the cell and go to the next cell
* [Shift]m - merge the selected cells
* x - cut the selected cells.
* v - paste the selected cells below.
* [Shift]v - paste the selected cells above.
* d,d - delete selected cells.

## Jupyter Magic Commands

Jupyter allows users to interact with the operating system (OS) using the escape character '!'. For example, on Linux or MacOS I can find which directory I am working in and list the contents of the current directory using the following commands:

In [1]:
!pwd # print current working directory

'pwd' 不是内部或外部命令，也不是可运行的程序
或批处理文件。


In [2]:
!ls # list contents of current directory

'ls' 不是内部或外部命令，也不是可运行的程序
或批处理文件。


Howevever if I am working in Windows, these commands will fail, since Windows does not use Unix commands. Instead Jupyter provides the following magic commands to interact with the OS:
* %cat - print the contents of a file
* %cd - change to another directory
* %cp - copy a file to another file
* %ls - list the contents of the current directory
* %mkdir - create a sub-directory in the current directory
* %mv - move or rename a file
* %pwd - print the current directory
* %rm - remove a file
* %rmdir - remove a subdirectory
The syntax for each of these can be found by using `help()` or `?`.

For example I can interact with the OS, in the following ways (of course there are easier ways to do this, like a GUI):

In [5]:
%ls # print the contents of the current directory

 驱动器 C 中的卷是 Windows-SSD
 卷的序列号是 B84B-B82F

 C:\Users\wsm\Downloads 的目录


 C:\Users\wsm\Downloads 的目录


 C:\Users\wsm\Downloads 的目录


 C:\Users\wsm\Downloads 的目录


 C:\Users\wsm\Downloads 的目录


 C:\Users\wsm\Downloads 的目录


 C:\Users\wsm\Downloads 的目录


 C:\Users\wsm\Downloads 的目录



找不到文件


In [13]:
%mkdir tmp# make a temporary directory call tmp

子目录或文件 make 已经存在。
处理: make 时出错。
子目录或文件 a 已经存在。
处理: a 时出错。
子目录或文件 temporary 已经存在。
处理: temporary 时出错。
子目录或文件 directory 已经存在。
处理: directory 时出错。
子目录或文件 call 已经存在。
处理: call 时出错。
子目录或文件 tmp 已经存在。
处理: tmp 时出错。


In [6]:
%ls # print the contents again, notice there is the new sub-directory

01-PythonIntroduction.ipynb*    ADS1001-GettingStarted.pdf*
01-PythonIntroductionFin.ipynb* BeginnerToAdvanced.ipynb*
02-PythonIntroduction.ipynb*    PythonIntroduction.ipynb*
03-PythonModules.ipynb          Untitled.ipynb*
ADS1001-GettingStarted.md*      tmp/


In [14]:
# copy a text file to the temporary directory (make sure you include the /)
%cp 03-PythonModules.ipynb tmp/

UsageError: Line magic function `%cp` not found.


In [8]:
%ls tmp # view the contents of the temporary directory

03-PythonModules.ipynb


In [9]:
# change to the temporary directory
%cd tmp 

/Users/src/BADS/ADS1001_2021/Lessons/tmp


In [8]:
%cat 03-PythonModules.ipynb # view the file in the current directory

UsageError: Line magic function `%cat` not found.


In [11]:
%rm 03-PythonModules.ipynb # remove the file we just viewed

In [12]:
# change to the parent directory
%cd ../ 

/Users/src/BADS/ADS1001_2021/Lessons


In [13]:
%rmdir tmp/ # remove the temporary directory

In [14]:
%ls # print the contents of directory, which now does not have a tmp directory

01-PythonIntroduction.ipynb*    ADS1001-GettingStarted.pdf*
01-PythonIntroductionFin.ipynb* BeginnerToAdvanced.ipynb*
02-PythonIntroduction.ipynb*    PythonIntroduction.ipynb*
03-PythonModules.ipynb          Untitled.ipynb*
ADS1001-GettingStarted.md*


Jupyter has many other magic commands, which can be investigated using the command `%magic`.

In [15]:
%magic

## Importing and Using Libraries

Libraries, packages and modules are various objects for using pre-written code. They are slightly different, however there usage is generally similar. Here we when we refer to libraries, generally the same applies for modules and packages.

There is only so much that can be done with the basic version of Python. The real power of Python comes from the libaries which have been developed for Python to perform specialised tasks. A few of the ones we will be dealing with in this studio are `numpy`, `matplotlib` and `pandas`. 

### The math library

The `math` library performs basic mathematics. To import this library we use the syntax:
* `import packagename`

When we are importing libraries using `import` or `from` (see later) statement, tab completion can be used to find the matching libraries.

For example to import the standard `math` package and access the help documentation we can use:

In [16]:
import math
help(math)

Help on module math:

NAME
    math

MODULE REFERENCE
    https://docs.python.org/3.7/library/math
    
    The following documentation is automatically generated from the Python
    source files.  It may be incomplete, incorrect or include features that
    are considered implementation detail and may vary between Python
    implementations.  When in doubt, consult the module reference at the
    location listed above.

DESCRIPTION
    This module provides access to the mathematical functions
    defined by the C standard.

FUNCTIONS
    acos(x, /)
        Return the arc cosine (measured in radians) of x.
    
    acosh(x, /)
        Return the inverse hyperbolic cosine of x.
    
    asin(x, /)
        Return the arc sine (measured in radians) of x.
    
    asinh(x, /)
        Return the inverse hyperbolic sine of x.
    
    atan(x, /)
        Return the arc tangent (measured in radians) of x.
    
    atan2(y, x, /)
        Return the arc tangent (measured in radians) of y/x.
    

This lists all the commands in the `math` package. To see all commands the commands we could use tab completion. In the following cell type `math.<TAB>` to see a listing of all the math functions. Then type `math.s<TAB>` to see the functions which start with 's'.

In [23]:
math.s<TAB>


SyntaxError: invalid syntax (<ipython-input-23-e21492e876f8>, line 1)

To use any of these functions or objects we use the syntax:
* `math.functionname()` for a function
* `math.object` for an object (e.g., a constant such as pi)

Again this syntax can be used with the `help()` or `?`.

In the following cell we can now perform some simple trigonometric calculations:

In [17]:
print('sin of pi/2 = ',math.sin(math.pi/2))
print("sin squared and cos squared =",math.sin(.6)**2+math.cos(.6)**2)


sin of pi/2 =  1.0
sin squared and cos squared = 1.0


If we don't want to write 'math' all the time for the functions we require, we can introduce an abbreviation for the package. Just make sure your abbreviation is not an already existing package, as this will create conflicts. For example in the following, `math` has been abbreviated to `m`:

In [18]:
import math as m

print('Square root of 2 is',m.sqrt(2))

Square root of 2 is 1.4142135623730951


If we only want a few functions or objects from a package we can import them using the `from` command. We then don't need to reference the package name before using them. Again tab completion can be used after `from` or `import`. For example if we want the natural exponent and logarithm, we can use:

In [19]:
from math import exp, log

The import list can be one function or object, or as long as we need. Now, we can use `exp` and `log` without the prefix:

In [20]:
print("Euler's constant is",exp(1))
print('The natural logarithm of 10 is',log(10))

Euler's constant is 2.718281828459045
The natural logarithm of 10 is 2.302585092994046


In the following cell import `sin`, `cos`, `tan` and `pi` using the `from` command, and calculate each of these for the arguments $0$, $\pi/6$, $\pi/4$, $\pi/3$ and $\pi/2$.

In [5]:
arguments = [0,pi/6,pi/4,pi/3,pi/2]
from math import sin,cos,tan,pi
for i in arguments:
    print('cos(i)=',cos(i),'sin(i)=',sin(i),'tan(i)=',tan(i))


cos(i)= 1.0 sin(i)= 0.0 tan(i)= 0.0
cos(i)= 0.8660254037844387 sin(i)= 0.49999999999999994 tan(i)= 0.5773502691896257
cos(i)= 0.7071067811865476 sin(i)= 0.7071067811865476 tan(i)= 0.9999999999999999
cos(i)= 0.5000000000000001 sin(i)= 0.8660254037844386 tan(i)= 1.7320508075688767
cos(i)= 6.123233995736766e-17 sin(i)= 1.0 tan(i)= 1.633123935319537e+16


### Numpy

`numpy` (short for Numerical Python) is the standard Python package for dealing with arrays and matrices, and is the basis for `pandas`, which is one of the standard libraries for Data Science. Hence, before dealing with `pandas` we will briefly introduce some of the features of `numpy`.

The basis of `numpy` is `ndarray` or the n-dimensional array, which is like Python lists, but enhanced for numerical mathematics. These can used to create vectors (one-dimensional arrays), matrices (two-dimensional arrays) and higher dimensional objects. Typically `numpy` is abbreviated as `np`, so we import it as:

In [21]:
import numpy as np

Then to create arrays we use

In [22]:
a = np.array([1,2,3,4])
b = np.array([5,6,7,8])

Compare this with creating a Python list

In [23]:
aa = [1,2,3,4]
bb = [5,6,7,8]

Now we can compare the results for addition and multiplication of these two objects:

In [24]:
print('Numpy addition gives',a+b)
print('Python addition gives',aa+bb)

print('Numpy multiplication gives',3*a)
print('Python multiplication gives',3*aa)

Numpy addition gives [ 6  8 10 12]
Python addition gives [1, 2, 3, 4, 5, 6, 7, 8]
Numpy multiplication gives [ 3  6  9 12]
Python multiplication gives [1, 2, 3, 4, 1, 2, 3, 4, 1, 2, 3, 4]


So, `numpy` gives algebraic operations, while Python lists give results which are consistent with the manipulation of strings. You can have `numpy` arrays which are strings, Boolean (True or False), floats or integers, but we will just deal with numbers here.

In the following cell define a vector `c=[-1,5,3]` and try to add this to `a`.

In [8]:
import numpy as np
a =np.array([1,2,3,4])
c= np.array([-1,5,3])
print(a+c)

ValueError: operands could not be broadcast together with shapes (4,) (3,) 

Hence the algebraic operations must follow particular rules.

Multiplication and division of two vectors of the same size now follows the "element-by-element" rule. In the following cell calculate `a*b` and `a/b`. How is each element of the resultant vector calculated?

We can also multiply two vectors of the same length together to calculate the "dot product". This is the sum of the "element-by-element" terms and the result is a scalar. This can be calculated using `np.dot`, `np.matmul` and `@`, as in the following examples:

In [25]:
print('The dot product of a and b can be written in the following ways:')
print('Sum of element by element multiplication',sum(a*b))
print('Using the dot product function',np.dot(a,b))
print('Using the matrix multiplication function',np.matmul(a,b))
print('Using the shortcut for matrix muliplication',a@b)

The dot product of a and b can be written in the following ways:
Sum of element by element multiplication 70
Using the dot product function 70
Using the matrix multiplication function 70
Using the shortcut for matrix muliplication 70


Two-dimensional arrays or matrices can be created by repeated use of square brackets. The inner elements define the first dimension or elements of each row, then the outer elements define the second dimension and move on to each row. The elements of each row, and each of the rows must be separated by commas. For example to define a 3 by 2 matrix we can use (typically capital letters are used for matrices):

In [26]:
A = np.array([[3,-1],[2,5],[7,-3]])
print(A)

[[ 3 -1]
 [ 2  5]
 [ 7 -3]]


To determine the number of dimensions of an array we can use the object `ndim`, to determine the size in each dimension we can use `shape` and to determine the total number of elements we can use `size`:

In [9]:
a = np.array([1,2,3,4])
A = np.array([[3,-1],[2,5],[7,-3]])
print('A has',A.ndim,'dimensions')
print('A has the shape',A.shape)
print('A has',A.size,'elements')

print('a has',a.ndim,'dimensions')
print('a has the shape',a.shape)
print('a has',a.size,'elements')

A has 2 dimensions
A has the shape (3, 2)
A has 6 elements
a has 1 dimensions
a has the shape (4,)
a has 4 elements


Now if two objects are compatible we can define matrix multiplication. For those unfamiliar with matrix multiplication, this corresponds to taking the dot product of all the rows of the first matrix with the columns of the second matrix, and will be introduced in MTH1020. If we have two matrices: `A` with size (m,n), and `B` with size (p,q), then to calculate `A@B` we must have n=p to be able to calculate the dot products, and the resultant matrix will have size (m,q). For a brief introduction see [Maths is Fun](https://www.mathsisfun.com/algebra/matrix-multiplying.html) or other websites. 

Here we will create a second matrix and multiply it with `A`:

In [13]:
A = np.array([[3,-1],[2,5],[7,-3]])
B = np.array([[3,-2],[0,2]])
C = A@B
print(C)
print(A.shape)
print(B.shape)


[[  9  -8]
 [  6   6]
 [ 21 -20]]
(3, 2)
(2, 2)


In the following cell, determine the shape of `C`. In this what you expect?

In [14]:
print(C.shape)
#must satisfy m*n n*r  and the result will be m*r

(3, 2)


What occurs if you try to calculate `B@A`?

In [15]:
B@A

ValueError: shapes (2,2) and (3,2) not aligned: 2 (dim 1) != 3 (dim 0)

We can also multiply vectors with matrices. Since `A` has 3 rows and 2 columns and `d` is a vector of length 3, we can multiply `d` with `A` to get a matrix with 2 columns:

In [32]:
import numpy as np
d = np.array([1,0,-1])
A = np.array([[3,-1],[2,5],[7,-3]])
print('The product of d and A is:')
print(d@A)
print(d.shape)
print(A.shape)
lower = int(input("输入区间最小值: "))
upper = int(input("输入区间最大值: "))
 # TODO
 # 请修改下面代码中的2个None
 
for num in range(lower,upper + 1):
     # 因为素数是大于 1的，所以如果数小于等于1就跳过。
    if num <= 1:
         continue
        for i in range(2,num + 1):
            if i != num and num % i == 0:
                break
            if i == num:
                print(num)

# 输出指定范围内的素数
lower = 3
upper = 100

# TODO
# 请修改下面代码中的2个None

for num in range(lower,upper + 1):
    # 因为素数是大于 1的，所以如果数小于等于1就跳过。
    if num <= 1:
        continue
    for i in range(2,num + 1):
        if i != num and num % i == 0:
            break
        if i == num:
            print(num)



IndentationError: unindent does not match any outer indentation level (<tokenize>, line 17)

As with lists we can use Python's indexing syntax to refer to parts of vectors or matrices. For example to refer to part of a vector we can use:

In [30]:
a = np.array([1,2,3,4])
print('First two elements of a are',a[0:2]) # prints the first two elements of a
print('Every second element of a are',a[0::2]) # prints every second element of a
print('a in reverse order is',a[-1::-1]) # prints the elements of a in reverse order

First two elements of a are [1 2]
Every second element of a are [1 3]
a in reverse order is [4 3 2 1]


This can be extended to matrices by separating the indices with commas, as in:

In [22]:
print('Original matrix is:')
print(A)
print('The matrix with shape (2,2) extracted from the top corner is:')
print(A[0:2,0:2]) # print the (2,2) matrix in the top corner of A
print('The third row is:')
print(A[2::]) #print the third row of A
print('The second column is:')
print(A[:,1]) # print the second column of A
prime_numbers=[]
min=3
max=101

for i in range(min,max):
  if i>1:
    for j in range(2,i):
        if(math.gcd(i,j)>1): #if gcd other than 1 exists, number is not prime
            break
    else:
        prime_numbers.append(i)

print(prime_numbers)

Original matrix is:
[[ 3 -1]
 [ 2  5]
 [ 7 -3]]
The matrix with shape (2,2) extracted from the top corner is:
[[ 3 -1]
 [ 2  5]]
The third row is:
[[ 7 -3]]
The second column is:
[-1  5 -3]


Print out the value in the first row and first column:

## Exercises

### Exercise 1

Use `math.gcd()` to create and print a list of all the primes up to 100. If a number is prime, then it is not divisible by all the smaller primes. Initialize your list with 2, start your search at 3, and use `list.append()` to add numbers to the list. You should use the function `max`.

In [15]:
lower = 3
upper = 100


primes =[2]
for num in range(lower,upper + 1):
   
    if num <= 1:
        continue
    for i in range(2,num + 1):
        if i != num and num % i == 0:
            break
        if i == num:
            primes.append(num)
print(primes)


        
 
     




                 

[2, 3, 5, 7, 11, 13, 17, 19, 23, 29, 31, 37, 41, 43, 47, 53, 59, 61, 67, 71, 73, 79, 83, 89, 97]


In [2]:
import math as math
allnumberin100=[]
for allnum in range(101):
    allnumberin100.append(allnum)
print(allnumberin100)
for x in allnumberin100:
    if math.gcd(x,num)==1:
        print(x)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, 100]


NameError: name 'num' is not defined

### Exercise 2

For the function $f(x) = 4\cos(3x)$, calculate the derivative and the approximation to the derivative $(f(x+h)-f(x-h))/(2h)$. Using $h=0.01$ find the maximum absolute difference between the derivative and the approximation for $x=[0,0.01,0.02,0.03,\dots,1.]$. You should use the functions `range`, `max` and `abs`.

In [31]:
import numpy as np 
a=[]
x = np.array(range(0,101))/100
for val in x:
    a.append(val)
from math import cos,sin,pi
import sympy as sp
x= sp.Symbol('x')
formula = sp.diff(4*sp.cos(3*x))
print(formula)
def f(x):
    return 4*sp.cos(3*x)
print(f(x))

def absdiff(x):
    
     return sp.diff(4*sp.cos(3*x)) - (f(x+0.01)-f(x-0.01))/(2*0.01) 
b = []
for i in a:
    b.append(absdiff(i))
    print('When  x={}, absolute difference between the derivative and the approximation is {}'.format(i,absdiff(i)))
import numpy as np
lst = np.array(b)
absoluteva=abs(lst)
print('The maximum absolute value is {}'.format(max(absoluteva)))







-12*sin(3*x)
4*cos(3*x)
When  x=0.0, absolute difference between the derivative and the approximation is 0
When  x=0.01, absolute difference between the derivative and the approximation is 0.359892012959162
When  x=0.02, absolute difference between the derivative and the approximation is 0.719460147398654
When  x=0.03, absolute difference between the derivative and the approximation is 1.07838081626759
When  x=0.04, absolute difference between the derivative and the approximation is 1.43633101519041
When  x=0.05, absolute difference between the derivative and the approximation is 1.79298861314896
When  x=0.06, absolute difference between the derivative and the approximation is 2.14803264237879
When  x=0.07, absolute difference between the derivative and the approximation is 2.50114358721836
When  x=0.08, absolute difference between the derivative and the approximation is 2.85200367165155
When  x=0.09, absolute difference between the derivative and the approximation is 3.20029714528474


### Exercise 3

The height of a projectile with initial position $x=0$, height $y=y_0$, speed $v=v_0$ and angle $\theta$ to the horizontal is given by $y(x) = x\tan(\theta)-\frac12 g(x/(v_0\cos(\theta))^2+y_0$, where $x$ is the horizontal position in m and $g$ is the acceleration of gravity. For $\theta = 45^\circ$, $v_0 = 10 ms^{-1}$, $g=9.81 ms^{-2}$ and $y_0 = 10 m$, print the height of the projectile at $x=[0,1,2,\dots,10]$.

In [121]:
x=[0,1,2,3,4,5,6,7,8,9,10]
from math import cos,tan,pi
def y(x):
    return i*(math.tan(pi/4))-0.5*9.81*(i/(-10)*(math.cos(pi/4)))**2+10
for i in x:
    print('When x= {}m, height is {}m'.format(i,y(i)))

                 
    

When x= 0m, height is 10.0m
When x= 1m, height is 10.975475m
When x= 2m, height is 11.9019m
When x= 3m, height is 12.779275m
When x= 4m, height is 13.6076m
When x= 5m, height is 14.386875m
When x= 6m, height is 15.117099999999999m
When x= 7m, height is 15.798274999999999m
When x= 8m, height is 16.4304m
When x= 9m, height is 17.013475m
When x= 10m, height is 17.5475m


### Exercise 4

Create a (3,3) array, $E$, which has values of 1 on the main diagonal, i.e., where the row and column number are the same, and values of 0 everywhere else. You should be able to do this using `np.array()` and `np.zeros()`. Create an arbitrary (3,3) matrix and a vector of length 3, and confirm that multiplying these arrays by $E$ does not change the arrays.

In [50]:
import numpy as np
E =  np.array([[1,0,0],[0,1,0],[0,0,1]])

a=np.zeros([3,3],dtype= int)
b=np.ones([3,3],dtype= int)
print(a)
print(b)
print(b@a)
print(E@E)
print(E ==E@E)







[[0 0 0]
 [0 0 0]
 [0 0 0]]
[[1 1 1]
 [1 1 1]
 [1 1 1]]
[[0 0 0]
 [0 0 0]
 [0 0 0]]
[[1 0 0]
 [0 1 0]
 [0 0 1]]
[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


### Exercise 5

Repeat Exercise 3, but use `np.linspace()` to create 21 evenly spaced values of $x$ in the range $0\le x\le 10$. You should not need to use a loop to calculate the $y$ values.

In [26]:
import numpy as np
x= np.linspace(0,10,21)
import math as math
from math import pi,cos
def y(x):
    return  x*(math.tan(pi/4))-0.5*9.81*(x/(-10)*(math.cos(pi/4)))**2+10
    
print(x)
print(y(x))
for i in x:
    print('When x ={}m, y(x)= {}m'.format(i,y(i)))
  

    








[ 0.   0.5  1.   1.5  2.   2.5  3.   3.5  4.   4.5  5.   5.5  6.   6.5
  7.   7.5  8.   8.5  9.   9.5 10. ]
[10.         10.49386875 10.975475   11.44481875 11.9019     12.34671875
 12.779275   13.19956875 13.6076     14.00336875 14.386875   14.75811875
 15.1171     15.46381875 15.798275   16.12046875 16.4304     16.72806875
 17.013475   17.28661875 17.5475    ]
When x =0.0m, y(x)= 10.0m
When x =0.5m, y(x)= 10.49386875m
When x =1.0m, y(x)= 10.975475m
When x =1.5m, y(x)= 11.44481875m
When x =2.0m, y(x)= 11.9019m
When x =2.5m, y(x)= 12.346718749999999m
When x =3.0m, y(x)= 12.779275m
When x =3.5m, y(x)= 13.19956875m
When x =4.0m, y(x)= 13.6076m
When x =4.5m, y(x)= 14.00336875m
When x =5.0m, y(x)= 14.386875m
When x =5.5m, y(x)= 14.758118749999998m
When x =6.0m, y(x)= 15.117099999999999m
When x =6.5m, y(x)= 15.463818749999998m
When x =7.0m, y(x)= 15.798274999999999m
When x =7.5m, y(x)= 16.12046875m
When x =8.0m, y(x)= 16.4304m
When x =8.5m, y(x)= 16.72806875m
When x =9.0m, y(x)= 17.013475m
